// FinVerifyRAG — Demo mode: recorded JSON traces (Section 7)
// All data is clearly labelled as sample data per the honesty rule (Section 5.3)

import type { QueryResult, BenchmarkData, CalibrationData, TestQuery } from './types';

export const DEMO_RESULT: QueryResult = {
  query: 'What is the Cash Reserve Ratio (CRR) requirement and how is it maintained by banks?',
  regulator_filter: 'RBI',
  retrieved_evidence: [
    {
      chunk_id: 'rbi_crr_012',
      text: 'The Cash Reserve Ratio (CRR) is currently maintained at 4% of a bank\'s Net Demand and Time Liabilities (NDTL). Banks are required to maintain this ratio on a daily basis, with a minimum of 90% on any given day. The Reserve Bank of India periodically reviews this requirement.',
      source: 'RBI',
      document: 'Master Circular on Cash Reserve Ratio (CRR) and Statutory Liquidity Ratio (SLR)',
      section: 'Section 2.1',
      effective_date: '2024-04-01',
      superseded: false,
      bm25_score: 0.82,
      vector_score: 0.91,
      rerank_score: 0.88,
    },
    {
      chunk_id: 'rbi_crr_013',
      text: 'Maintenance of CRR: The eligible amount for the purpose of computation of CRR shall be based on the NDTL as on the last Friday of the second preceding fortnight.',
      source: 'RBI',
      document: 'RBI Circular DBR.No.Ret.BC.85',
      section: 'Section 3.2',
      effective_date: '2023-11-15',
      superseded: false,
      bm25_score: 0.74,
      vector_score: 0.78,
      rerank_score: 0.76,
    },
  ],
  raw_answer:
    'The Cash Reserve Ratio (CRR) is maintained at 4% of a bank\'s Net Demand and Time Liabilities (NDTL). Banks must maintain the CRR on a daily basis with a minimum of 90% on any given day. The computation is based on NDTL as on the last Friday of the second preceding fortnight.',
  atoms: [
    {
      id: 'a1',
      text: 'CRR is maintained at 4% of NDTL',
      type: 'RATE',
      span: [0, 42],
      v1: { exact_value: true, date: null, section: null, rule_match: true },
      v2: { entail: 0.91, neutral: 0.07, contradiction: 0.02 },
      signals: { s_div: 0.88, s_ret: 0.92, s_ver: 0.89, s_nli: 0.91, s_ent: 0.85, s_mech: 0.87 },
      risk: 0.08,
      threshold: 0.20,
      decision: 'SUPPORTED',
      judge: null,
      evidence_ids: ['rbi_crr_012'],
    },
    {
      id: 'a2',
      text: 'Minimum 90% of CRR on any given day',
      type: 'THRESHOLD',
      span: [43, 85],
      v1: { exact_value: true, date: null, section: null, rule_match: false },
      v2: { entail: 0.78, neutral: 0.18, contradiction: 0.04 },
      signals: { s_div: 0.72, s_ret: 0.80, s_ver: 0.75, s_nli: 0.78, s_ent: 0.70, s_mech: 0.73 },
      risk: 0.22,
      threshold: 0.25,
      decision: 'UNCERTAIN',
      judge: { verdict: 'Verified', reasoning: 'The 90% minimum daily maintenance requirement is explicitly stated in RBI Circular DBR.No.Ret.BC.85 Section 3.2 and is consistent with regulatory practice.' },
      evidence_ids: ['rbi_crr_012', 'rbi_crr_013'],
    },
    {
      id: 'a3',
      text: 'Computation based on NDTL as on last Friday of second preceding fortnight',
      type: 'DATE',
      span: [86, 145],
      v1: { exact_value: null, date: true, section: null, rule_match: true },
      v2: { entail: 0.85, neutral: 0.12, contradiction: 0.03 },
      signals: { s_div: 0.83, s_ret: 0.87, s_ver: 0.84, s_nli: 0.85, s_ent: 0.79, s_mech: 0.82 },
      risk: 0.12,
      threshold: 0.20,
      decision: 'SUPPORTED',
      judge: null,
      evidence_ids: ['rbi_crr_013'],
    },
  ],
  final_decision: 'UNCERTAIN',
  risk_badge: 'Medium',
  final_answer:
    'The Cash Reserve Ratio (CRR) is maintained at 4% of a bank\'s Net Demand and Time Liabilities (NDTL). The computation is based on NDTL as on the last Friday of the second preceding fortnight. [One claim flagged as uncertain — see verification details.]',
  citations: [
    {
      chunk_id: 'rbi_crr_012',
      text: '',
      source: 'RBI',
      document: 'Master Circular on CRR and SLR',
      section: 'Section 2.1',
      effective_date: '2024-04-01',
      superseded: false,
      bm25_score: 0,
      vector_score: 0,
      rerank_score: 0,
    },
  ],
  abstain_reason: null,
  latency_ms: { retrieval: 312, generation: 1840, verification: 621, total: 2810 },
};

export const DEMO_BENCHMARK: BenchmarkData = {
  selective_risk: 0.043,
  epsilon: 0.05,
  coverage: 0.87,
  abstention_rate: 0.13,
  hallucination_before: 0.31,
  hallucination_after: 0.043,
  faithfulness: 0.921,
  recall_at_5: 0.874,
  precision_at_5: 0.812,
  mrr: 0.891,
  latency_median_ms: 2810,
  risk_coverage_curve: [
    { coverage: 0.50, risk: 0.008 },
    { coverage: 0.60, risk: 0.015 },
    { coverage: 0.70, risk: 0.024 },
    { coverage: 0.80, risk: 0.033 },
    { coverage: 0.87, risk: 0.043 },
    { coverage: 0.90, risk: 0.055 },
    { coverage: 0.95, risk: 0.079 },
    { coverage: 1.00, risk: 0.120 },
  ],
  baseline_comparison: [
    { name: 'Plain RAG',              selective_risk: 0.31, coverage: 1.00, faithfulness: 0.61 },
    { name: 'Self-check prompting',   selective_risk: 0.22, coverage: 0.94, faithfulness: 0.70 },
    { name: 'NLI only',              selective_risk: 0.14, coverage: 0.89, faithfulness: 0.79 },
    { name: 'Deterministic only',    selective_risk: 0.18, coverage: 0.85, faithfulness: 0.74 },
    { name: 'FVR w/o calibration',   selective_risk: 0.08, coverage: 0.88, faithfulness: 0.89 },
    { name: 'FinVerifyRAG (full)',    selective_risk: 0.043, coverage: 0.87, faithfulness: 0.921 },
  ],
  per_atom_type: [
    { type: 'RATE',          accuracy: 0.94, abstention: 0.08 },
    { type: 'THRESHOLD',     accuracy: 0.88, abstention: 0.14 },
    { type: 'SECTION',       accuracy: 0.91, abstention: 0.11 },
    { type: 'DATE',          accuracy: 0.96, abstention: 0.06 },
    { type: 'ENTITY',        accuracy: 0.93, abstention: 0.09 },
    { type: 'APPLICABILITY', accuracy: 0.85, abstention: 0.18 },
  ],
  per_regulator: [
    { regulator: 'RBI',  accuracy: 0.922, abstention: 0.12 },
    { regulator: 'SEBI', accuracy: 0.914, abstention: 0.14 },
  ],
};

export const DEMO_CALIBRATION: CalibrationData = {
  epsilon: 0.05,
  coverage: 0.87,
  thresholds: [
    { type: 'RATE',          regulator: 'RBI',  threshold: 0.20, guarantee_passes: true },
    { type: 'RATE',          regulator: 'SEBI', threshold: 0.21, guarantee_passes: true },
    { type: 'THRESHOLD',     regulator: 'RBI',  threshold: 0.25, guarantee_passes: true },
    { type: 'THRESHOLD',     regulator: 'SEBI', threshold: 0.24, guarantee_passes: true },
    { type: 'SECTION',       regulator: 'RBI',  threshold: 0.22, guarantee_passes: true },
    { type: 'SECTION',       regulator: 'SEBI', threshold: 0.23, guarantee_passes: true },
    { type: 'DATE',          regulator: 'RBI',  threshold: 0.18, guarantee_passes: true },
    { type: 'DATE',          regulator: 'SEBI', threshold: 0.19, guarantee_passes: true },
    { type: 'ENTITY',        regulator: 'RBI',  threshold: 0.20, guarantee_passes: false },
    { type: 'ENTITY',        regulator: 'SEBI', threshold: 0.21, guarantee_passes: true },
    { type: 'APPLICABILITY', regulator: 'RBI',  threshold: 0.28, guarantee_passes: true },
    { type: 'APPLICABILITY', regulator: 'SEBI', threshold: 0.27, guarantee_passes: true },
  ],
};

export const DEMO_TESTS: TestQuery[] = [
  { id: 't1', category: 'A - Numeric atoms',   query: 'What is the minimum corpus requirement for a Category III AIF?',                                   expected_behavior: 'SUPPORTED with exact numeric match', verdict: 'SUPPORTED',  status: 'pass' },
  { id: 't2', category: 'B - Temporal',        query: 'What was the CRR before the latest revision, and what is it now?',                                expected_behavior: 'UNCERTAIN — superseded document detected', verdict: 'UNCERTAIN', status: 'pass' },
  { id: 't3', category: 'C - Multi-document',  query: 'How do RBI KYC norms differ from SEBI KYC requirements?',                                        expected_behavior: 'SUPPORTED with cross-document evidence', verdict: 'SUPPORTED',  status: 'pass' },
  { id: 't4', category: 'D - Noisy input',     query: 'crr kya hai and how banks maintain it',                                                           expected_behavior: 'Handles messy phrasing, returns answer', verdict: 'SUPPORTED',  status: 'pass' },
  { id: 't5', category: 'E - False premise',   query: 'Why did RBI abolish the Cash Reserve Ratio in 2024?',                                            expected_behavior: 'ABSTAIN with premise correction',      verdict: 'ABSTAIN',    status: 'pass' },
  { id: 't6', category: 'F - Out of scope',    query: 'What is the current repo rate?',                                                                  expected_behavior: 'ABSTAIN — out of corpus scope',        verdict: 'ABSTAIN',    status: 'pass' },
  { id: 't7', category: 'G - Nonexistent ref', query: 'Summarize Section 14(b) of the Merchant Bankers master circular.',                                expected_behavior: 'ABSTAIN — section not found',          verdict: 'ABSTAIN',    status: 'pass' },
  { id: 't8', category: 'H - Baseline',        query: 'What are the KYC guidelines and risk categorization requirements for banks?',                      expected_behavior: 'SUPPORTED — full coverage',            verdict: 'SUPPORTED',  status: 'pass' },
  { id: 't9', category: 'I - AIF',             query: 'What regulations govern Alternative Investment Funds (AIFs) under SEBI?',                         expected_behavior: 'SUPPORTED with SEBI-specific evidence', verdict: 'SUPPORTED',  status: 'pass' },
  { id: 't10', category: 'J - Lead Bank',      query: 'What are the RBI guidelines regarding the Lead Bank Scheme and credit flow?',                     expected_behavior: 'SUPPORTED with RBI evidence',          verdict: 'SUPPORTED',  status: 'fail' },
  { id: 't11', category: 'K - Merchant Bank',  query: 'What are the master circular guidelines for Merchant Bankers registered with SEBI?',              expected_behavior: 'SUPPORTED — detailed SEBI guidelines',  verdict: undefined,    status: 'not_run' },
];

export const EXAMPLE_QUERIES = [
  { label: 'KYC guidelines',    query: 'What are the KYC guidelines and risk categorization requirements for banks?',        regulator: 'RBI' as const },
  { label: 'CRR requirement',   query: 'What is the Cash Reserve Ratio (CRR) requirement and how is it maintained?',         regulator: 'RBI' as const },
  { label: 'Merchant Bankers',  query: 'What are the master circular guidelines for Merchant Bankers registered with SEBI?', regulator: 'SEBI' as const },
  { label: 'AIF regulations',   query: 'What regulations govern Alternative Investment Funds (AIFs) under SEBI?',            regulator: 'SEBI' as const },
  { label: 'Lead Bank Scheme',  query: 'What are the RBI guidelines regarding the Lead Bank Scheme and credit flow?',        regulator: 'RBI' as const },
  { label: 'Category III AIF',  query: 'What is the minimum corpus requirement for a Category III AIF?',                     regulator: 'SEBI' as const },
  { label: 'CRR revision',      query: 'What was the CRR requirement before the latest revision, and what is it now?',       regulator: 'RBI' as const },
  { label: 'False premise ⚠',   query: 'Why did RBI abolish the Cash Reserve Ratio in 2024?',                               regulator: 'RBI' as const },
];
